apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-api-config
  namespace: {{ .Values.namespace }}
  labels:
    app: fogcloud
data:
  default.conf: |+
    server {
      listen 80;
      server_name  localhost;
      underscores_in_headers on;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Real-Port $remote_port;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  

      location /api/ {
        proxy_pass http://fogcloud:4000/api/;
      }

      location /ping {
          return 200 "ok";
      }

      location /openapi/ {
        proxy_pass http://fogcloud:4000/openapi/;
      }

      {{- if .Values.fissionEnabled -}}
      location /faas/functions/ {
        proxy_pass http://router.fission.svc.cluster.local/;
      }
      {{ end }}

      location /api/v1/oss/ {
          proxy_pass http://fogcloud:4000/api/v1/oss/;

          proxy_cache mycache;
          slice 1m;
          proxy_cache_key    $host$uri$is_args$args$slice_range;
          proxy_set_header   Range $slice_range;
          proxy_cache_valid 200 206 1d;
          proxy_cache_methods GET;
          add_header Accept-Ranges bytes;
      }  
    }