apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-api-config
  
  labels:
    app: fogcloud
data:
  default.conf: |+
    upstream fogcloud {
      server fogcloud:4000;
      keepalive 1000;
    }

    upstream fognotifier {
      server fognotifier:8200;
      keepalive 1000;
    }

    {{ if .Values.tdengineEnabled }}
    upstream fogthinghistory {
      server fogthinghistory:8300;
      keepalive 1000;
    }
    {{ end }}

    {{ if .Values.fissionEnabled }}
    upstream faas {
      server router.fission.svc.cluster.local:80;
      keepalive 100;
    }
    {{ end }}

    server {
      listen 80;
      server_name  localhost;
      underscores_in_headers on;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Real-Port $remote_port;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      location /api/ {
        proxy_pass http://fogcloud/api/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
      }

      location /ping {
          default_type text/html;
          return 200 "pong";
      }

      location /openapi/ {
        proxy_pass http://fogcloud/openapi/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
      }

      location /openapp/ {
        proxy_pass http://fogcloud/openapp/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
      }

      {{ if .Values.fissionEnabled }}
      location /faas/functions/ {
        proxy_pass http://faas/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
      }
      {{ end }}

      location /api/v1/oss/ {
          proxy_pass http://fogcloud/api/v1/oss/;

          proxy_cache mycache;
          slice 1m;
          proxy_cache_key    $host$uri$is_args$args$slice_range;
          proxy_set_header   Range $slice_range;
          proxy_cache_valid 200 206 1d;
          proxy_cache_methods GET;
          add_header Accept-Ranges bytes;
      }

      location /fognotifier/ {
          proxy_pass http://fognotifier/fognotifier/;
      }

      {{ if .Values.tdengineEnabled }}
      location /fogthinghistory/ {
          proxy_pass http://fogthinghistory/fogthinghistory/;
      }
      {{ end }}
    }