apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-web-config
  
  labels:
    app: fogcloud
data:
  default.conf: |+
    server {
        listen 8000;
        server_name localhost;

        location / {
            root   /app/www/fogcloud_web;
            index  index.html index.htm;
            try_files $uri $uri/index.html $uri.html=404;
        }

        location /ping {
            default_type text/html;
            return 200 "pong";
        }

        {{ if .Values.expose.insecureOSS }}
        location /api {
          return 301 http://{{ .Values.expose.hosts.api }}$request_uri;
        }
        {{ else }}
        location /api {
          return 301 https://{{ .Values.expose.hosts.api }}$request_uri;
        }
        {{ end }}

        {{ if .Values.expose.tls.enabled }}
        location /faas {
          return 301 https://{{ .Values.expose.hosts.api }}$request_uri;
        }
        {{ else }}
        location /faas {
          return 301 http://{{ .Values.expose.hosts.api }}$request_uri;
        }
        {{ end }}
    }