apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-web-config
  namespace: {{ .Values.namespace }}
  labels:
    app: fogcloud
data:
  default.conf: |+
    server {
        listen 8000;
        server_name localhost;

        location / {
            root   /app/www/fogcloud_web;
            index  index.html index.htm;
            try_files $uri $uri/index.html $uri.html=404;
        }

        {{ if .Values.expose.insecureOSS }}
        location /api/v1/oss {
          return 302 http://{{ .Values.expose.hosts.api }}$request_uri;
        }
        {{ else }}
        location /api/v1/oss {
          return 302 https://{{ .Values.expose.hosts.api }}$request_uri;
        }
        {{ end }}

        {{ if .Values.expose.tls.enabled }}
        location /faas {
          return 302 https://{{ .Values.expose.hosts.api }}$request_uri;
        }
        {{ else }}
        location /faas {
          return 302 http://{{ .Values.expose.hosts.api }}$request_uri;
        }
        {{ end }}
    }