# nginx-service
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    srv: nginx
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  {{ if eq .Values.expose.type "Ingress" }}
  type: ClusterIP
  {{ else if eq .Values.expose.type "LoadBalancer" }}
  type: NodePort
  {{ else }}
  type: {{ .Values.expose.type }}
  {{ end }}
  {{ if eq .Values.expose.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.expose.LoadBalancer.externalTrafficPolicy }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.expose.LoadBalancer.ports.api.httpPort }}
  {{ end }} 
  {{ if eq .Values.expose.type "NodePort" }}
  externalTrafficPolicy: {{ .Values.expose.NodePort.externalTrafficPolicy }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.expose.NodePort.ports.api.httpPort }}
  {{ end }}   
  {{ if or (eq .Values.expose.type "Ingress") (eq .Values.expose.type "ClusterIP") }}
  ports:
    - name: http
      port: 80
      targetPort: 80
  {{ end }}
  selector:
    app: nginx
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    app: nginx
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: {{ .Values.nginx.image }}:{{ .Values.nginx.imageTag }}
          name: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          {{- if .Values.nginx.resources }}
          resources:
{{ toYaml .Values.nginx.resources | indent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: default-claim
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-claim
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: nginx
              topologyKey: "kubernetes.io/hostname"    
      volumes:
        - name: nginx-claim
          configMap:
            name: fog-config
            items:
              - key: nginx.conf
                path: nginx.conf  
        - name: default-claim
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf              
status: {}