{{ if eq .Values.postgres.type "internal" }}
{{ $app := .Values.postgres.internal }}
# postgres-service
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    srv: postgres
  name: postgres
  
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Pod
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    app: postgres
  name: postgres
  
spec:
  containers:
    - env:
        {{ range $fields := $app.envVars }}
        - name: {{ $fields.name }}
          value: "{{ $fields.value }}"
        {{ end }}  
      image: {{ $app.image }}:{{ $app.imageTag }}
      name: postgres
      ports:
        - containerPort: 5432
      {{- if $app.resources }}
      resources:
{{ toYaml $app.resources | indent 8 }}
      {{- end }}
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
  restartPolicy: Always
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: {{ $app.persistence.pvc }}
status: {}
{{ end }}
