{{ $autoWeb := eq .Values.expose.tls.cert.webAdmin.certSource "auto" }}
{{ $autoApi := eq .Values.expose.tls.cert.api.certSource "auto" }}
{{ if or $autoWeb $autoApi }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-fog
  
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:
    privateKeySecretRef:
      name: letsencrypt-fog
    solvers:
      - selector: {}
        http01:
          ingress:
            class: {{ .Values.expose.Ingress.className }}
{{ end }}            