apiVersion: v1
kind: ConfigMap
metadata:
  name: fog-config
  namespace: {{ .Values.namespace }}
data:
  {{ range $path, $bytes := .Files.Glob "configs/fogcloud-core/*" }}
  fogcloud.yaml: |-
    {{ $bytes | toString | nindent 4 }}
  {{ end }}

  {{ range $path, $bytes := .Files.Glob "configs/fogcron/*" }}
  fogcron.yaml: |-
    {{ $bytes | toString | nindent 4 }}
  {{ end }}

  {{ range $path, $bytes := .Files.Glob "configs/faasbuilder/*" }}
  faasbuilder.yaml: |-
    {{ $bytes | toString | nindent 4 }}
  {{ end }}

  {{ range $path, $bytes := .Files.Glob "configs/kubeconfig/*" }}
  kubeconfig: |-
    {{ $bytes | toString | nindent 4 }}
  {{ end }}

  {{ if .Values.mqttBroker.enabled }}
  {{ range $path, $bytes := .Files.Glob "configs/emq/*" }}
  {{ $path | base }}: |-
    {{ $bytes | toString | nindent 4 }}
  {{ end }}
  {{ end }}

  {{ range $path, $bytes := .Files.Glob "configs/hmq/*" }}
  {{ $path | base }}: |-
    {{ $bytes | toString | nindent 4 }}
  {{ end }}

  {{ range $path, $bytes := .Files.Glob "configs/nginx/*" }}
  {{ $path | base }}: |-
    {{ $bytes | toString | nindent 4 }}
  {{ end }}
  
  {{ if .Values.rabbitmq.enabled }}
  {{ range $path, $bytes := .Files.Glob "configs/rabbitmq/*" }}
  {{ $path | base }}: |-
    {{ $bytes | toString | nindent 4 }}
  {{ end }}
  {{ end }}

