# fogcloud-service
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    srv: fogcloud
  name: fogcloud
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 4000
      targetPort: 4000
    - name: "http-debug"
      port: 4001
      targetPort: 15000  
  selector:
    app: fogcloud
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dep: fogcloud
  name: fogcloud
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.fogcloud.replicas }}
  selector:
    matchLabels:
      app: fogcloud
  strategy:
    type: {{ .Values.fogcloud.strategy.type }}
    {{ if eq .Values.fogcloud.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.fogcloud.strategy.rollingUpdate.maxSurge | default "50%" }}
      maxUnavailable: {{ .Values.fogcloud.strategy.rollingUpdate.maxUnavailable | default 0 }}
    {{ end }}

  template:
    metadata:
      annotations:
      labels:
        app: fogcloud
    spec:
      containers:
        - args:
            - fogcloud
            - -c
            - /etc/fogcloud/config.example.yaml
            - -e
            - {{ .Values.environment }}
          image: {{ .Values.fogcloud.image }}:{{ .Values.fogcloud.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: fogcloud
          ports:
            - containerPort: 4000
            - containerPort: 15000
          volumeMounts:
            - mountPath: /etc/fogcloud/config.example.yaml
              subPath: config.example.yaml
              name: fogcloud-claim
            # - mountPath: /etc/fogcloud/active.en.json
            #   subPath: active.en.json
            #   name: fogcloud-claim
            # - mountPath: /etc/fogcloud/active.zh.json
            #   subPath: active.zh.json
            #   name: fogcloud-claim
      restartPolicy: {{ .Values.fogcloud.restartPolicy }}
      imagePullSecrets:
        {{ range $_, $secret := .Values.secret.imageCredentials }}
        - name: {{ $secret.name }}
        {{ end }}
      volumes:
        - name: fogcloud-claim
          configMap:
            name: fog-config
            items:
              - key: config.example.yaml
                path: config.example.yaml
              # - key: active.en.json
              #   path: active.en.json
              # - key: active.zh.json
              #   path: active.zh.json
status: {}
