{{ if eq .Values.expose.type "Ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.expose.Ingress.annotations | indent 4 }}
  labels:
    ing: fogcloud-ingress
  name: fogcloud-ingress
  namespace: {{ .Values.namespace }}
spec:
  {{ if .Values.expose.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.expose.hosts.webAdmin }}"
      secretName: {{ .Values.expose.tls.cert.webAdmin.secretName }}
    - hosts:
        - "{{ .Values.expose.hosts.api }}"
      secretName: {{ .Values.expose.tls.cert.api.secretName }}
  {{ end }}    
  ingressClassName: {{ .Values.expose.Ingress.className }} #import !!!
  rules:
    - host: {{ .Values.expose.hosts.webAdmin }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fogcloud-web
                port:
                  number: 4002
          - path: /api/v1/oss/
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80 
          - path: /faas/functions/
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80                
    - host: {{ .Values.expose.hosts.api }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80     
          - path: /openapi/
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80                                  
{{ end }}                  