{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingress.className }}
  namespace: {{ .Values.namespace }}
spec:
  controller: {{ .Values.ingress.controller }}
{{ end }}