{{ if eq .Values.redis.type "internal" }}
{{ $persistence := .Values.redis.internal.persistence }}
{{ if not $persistence.existed }}
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: redis-pv
# spec:
#   capacity:
#     storage: 1Gi
#   hostPath:
#     path: /var/lib/rancher/k3s/storage/fogcloud-dev/redis-pv
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: ""
#   claimRef:
#     name: redis-pvc
#     
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    {{ if $persistence.keep }}
    "helm.sh/resource-policy": keep
    {{ end }}
  labels:
    pvc: redis-data
  name: {{ $persistence.pvc }}
  
spec:
  storageClassName: {{ $persistence.storageClassName }}
  # volumeName: redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ $persistence.storage }}"
status: {}
{{ end }}
{{ end }}