{{ if eq .Values.redis.type "internal" }}
{{ $app := .Values.redis.internal }}
# redis-service
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    srv: redis
  name: redis
  
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Pod
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    app: redis
  name: redis
  
spec:
  containers:
    - image: {{ $app.image }}:{{ $app.imageTag }}
      name: redis
      env:
        {{ range $fields := $app.envVars }}
        - name: {{ $fields.name }}
          value: "{{ $fields.value }}"
        {{ end }}        
      ports:
        - containerPort: 6379
      {{- if $app.resources }}
      resources: 
{{ toYaml $app.resources | indent 8 }}
      {{- end }}
      volumeMounts:
        - mountPath: /data
          name: redis-data
  restartPolicy: Always
  volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: {{ $app.persistence.pvc }}
status: {}
{{ end }}