apiVersion: v2
name: fogcloud
description: A Helm chart for fogcloud

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v5.3.0"

home: https://fogcloud.io

sources:
  - https://github.com/fogcloud-io/fogcloud-charts

dependencies:
  - name: nats
    version: "1.1.4"
    repository: "file://../nats"
    condition: nats.enabled
  - name: common
    version: "2.13.3"
    repository: "file://../common"
  - name: etcd-cluster
    version: "9.10.5"
    repository: "file://../etcd-cluster"
    condition: etcd-cluster.enabled
  - name: redis-cluster
    version: "18.3.2"
    repository: "file://../redis-cluster"
    condition: redis-cluster.enabled
  - name: minio-cluster
    version: "12.9.3"
    repository: "file://../minio-cluster"
    condition: minio-cluster.enabled
  - name: tdengine
    version: "3.0.2"
    repository: "file://../tdengine"
    condition: tdengine.enabled