{{ if eq .Values.mongodb.type "internal" }}
{{ $persistence := .Values.mongodb.internal.persistence }}
{{ if not $persistence.existed }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    {{ if $persistence.keep }}
    "helm.sh/resource-policy": keep
    {{ end }}
  labels:
    pvc: mongo-data
  name: mongo-pvc
  
spec:
  storageClassName: {{ $persistence.storageClassName }}
  # volumeName: mongo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ $persistence.storage }}"
status: {}
{{ end }}
{{ end }}