{{ if .Values.mongodb.enabled }}
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo-pv
# spec:
#   capacity:
#     storage: 5Gi
#   hostPath:
#     path: /var/lib/rancher/k3s/storage/fogcloud-dev/mongo-pv
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: "local-path"
#   claimRef:
#     name: mongo-pvc
#     namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: mongo-data
  name: mongo-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  # volumeName: mongo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
{{ end }}