{{ if eq .Values.mongodb.type "internal" }}
# mongo-service
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    srv: mongo
  name: mongo
  
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Pod
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    app: mongo
  name: mongo
  
spec:
  containers:
    - image: {{ .Values.mongodb.internal.image }}:{{ .Values.mongodb.internal.imageTag }}
      name: mongo
      env:
        {{ range $fields := .Values.mongodb.internal.envVars }}
        - name: {{ $fields.name }}
          value: "{{ $fields.value }}"
        {{ end }}  
      ports:
        - containerPort: 27017
      {{- if .Values.mongodb.internal.resources }}
      resources:
{{ toYaml .Values.mongodb.internal.resources | indent 8 }}
      {{- end }}
      volumeMounts:
        - mountPath: /data/db
          name: mongo-data
  restartPolicy: Always
  volumes:
    - name: mongo-data
      persistentVolumeClaim:
        claimName: mongo-pvc
status: {}
{{ end }}