{{ if .Values.mongodb.enabled }}
# mongo-service
apiVersion: v1
kind: Service
metadata:
  labels:
    srv: mongo
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  containers:
    - image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.imageTag }}
      name: mongo
      env:
        {{ range $fields := .Values.mongodb.envVars }}
        - name: {{ $fields.name }}
          value: "{{ $fields.value }}"
        {{ end }}  
      ports:
        - containerPort: 27017
      resources: {}
      volumeMounts:
        - mountPath: /data/db
          name: mongo-data
  restartPolicy: Always
  volumes:
    - name: mongo-data
      persistentVolumeClaim:
        claimName: mongo-pvc
status: {}
{{ end }}