{{ if eq .Values.mqttBroker.type "internal" }}
{{ if eq .Values.mqttBroker.internal.type "emqx" }}
{{ $app := .Values.mqttBroker.internal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-auth-mnesia-config
  labels:
    app: fogcloud
data:
  emqx_auth_mnesia.conf: |+
    auth.user.1.username = {{ $app.defaultUsername }}
    auth.user.1.password = {{ $app.defaultPassword }}
{{ end }}                
{{ end }}    