{{ if eq .Values.minio.type "internal" }}
{{ $persistence := .Values.minio.internal.persistence }}
{{ if not $persistence.existed }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    pvc: minio-data
  name: {{ $persistence.pvc }}
  
spec:
  storageClassName: {{ $persistence.storageClassName }}
  # volumeName: minio-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ $persistence.storage }}"
status: {}
{{ end }}
{{ end }}