{{ if eq .Values.minio.type "internal" }}
{{ $app := .Values.minio.internal }}
{{ $svcType := .Values.minio.internal.service.type | default "ClusterIP" }}
# minio-service
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    srv: fogcloud-minio
  name: fogcloud-minio
  
spec:
  type: {{ $svcType }}
  {{ if or (eq $svcType "NodePort") (eq $svcType "LoadBalancer") }}
  externalTrafficPolicy: "Local"
    {{ if and (eq $app.service.externalTrafficPolicy "Local") (eq $svcType "LoadBalancer") }}
  healthCheckNodePort: {{ $app.service.healthCheckNodePort }}
    {{ end }}
  {{ end }}
  ports:
    - name: "api"
      port: 9000
      targetPort: 9000
      {{ if or (eq $svcType "NodePort") (eq $svcType "LoadBalancer") }}
      nodePort: {{ $app.service.nodePorts.api }}
      {{ end }}
    - name: "console"
      port: 9001
      targetPort: 9001
      {{ if or (eq $svcType "NodePort") (eq $svcType "LoadBalancer") }}
      nodePort: {{ $app.service.nodePorts.console }}
      {{ end }}
  selector:
    app: minio
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Pod
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    app: minio
  name: minio
  
spec:
  containers:
    - name: minio
      env:
        {{ range $fields := $app.envVars }}
        - name: {{ $fields.name }}
          value: "{{ $fields.value }}"
        {{ end }}
      args:
        - server
        - --console-address
        - :9001
        - /data
      image: {{ $app.image }}:{{ $app.imageTag }}
      ports:
        - containerPort: 9000
        - containerPort: 9001
      {{- if $app.resources }}
      resources:
{{ toYaml $app.resources | indent 8 }}
      {{- end }}
      volumeMounts:
        - mountPath: /data
          name: minio-data
  restartPolicy: Always
  volumes:
    - name: minio-data
      persistentVolumeClaim:
        claimName: {{ $app.persistence.pvc }}
status: {}
{{ end }}