{{ if .Values.rabbitmq.enabled }}
# rabbitmq-service
apiVersion: v1
kind: Service
metadata:
  labels:
    srv: rabbitmq
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  {{ if or (eq .Values.rabbitmq.service.type "NodePort") (eq .Values.rabbitmq.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.rabbitmq.service.externalTrafficPolicy }}
    {{ if and (eq .Values.rabbitmq.service.externalTrafficPolicy "Local") (eq .Values.rabbitmq.service.type "LoadBalancer") }}
  healthCheckNodePort: {{ .Values.rabbitmq.service.healthCheckNodePort }}
    {{ end }}
  {{ end }}
  ports:
    {{ $svcType := .Values.rabbitmq.service.type }}
    {{ range $port := .Values.rabbitmq.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      {{ if eq $svcType "NodePort" }}
      nodePort: {{ $port.nodePort }}
      {{ end }}
    {{ end }}
  selector:
    app: rabbitmq
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  containers:
    - env:
        - name: RABBITMQ_CONFIG_FILE
          value: /etc/rabbitmq/rabbitmq.conf
        {{ if .Values.rabbitmq.tls.enabled }}  
        - name: RABBITMQ_LISTENERS_SSL_1
          value: 5671       
        - name: RABBITMQ_SSL__OPTIONS_VERIFY
          value: "verify_peer"    
        - name: RABBITMQ_SSL__OPTIONS_FAIL__IF__NO__PEER__CERT
          value: false                 
        - name: RABBITMQ_SSL__OPTIONS_CACERTFILE
          value: "/etc/rabbimq/tls.crt"
        - name: RABBITMQ_SSL__OPTIONS_CERTFILE
          value: "/etc/rabbimq/tls.crt"
        - name: RABBITMQ_SSL__OPTIONS_KEYFILE
          value: "/etc/rabbimtq/tls.key"
        - name: RABBITMQ_SSL__OPTIONS_VERSION_2
          value: "tlsv1.2"          
        {{ end }}  
      image: {{ .Values.rabbitmq.image }}:{{ .Values.rabbitmq.imageTag }}
      name: rabbitmq
      ports:
        - containerPort: 15672
        - containerPort: 5672
      resources: {}
      volumeMounts:
        - mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
          name: rabbitmq-claim
        - mountPath: /etc/rabbitmq/enabled_plugins
          subPath: enabled_plugins
          name: rabbitmq-claim
        {{ if .Values.rabbitmq.tls.enabled }}  
        - mountPath: /etc/rabbitmq/tls.crt
          subPath: tls.crt
          name: rabbitmq-secret
        - mountPath: /etc/rabbitmq/tls.key
          subPath: tls.key
          name: rabbitmq-secret   
        {{ end }}         
  restartPolicy: Always
  volumes:
    - name: rabbitmq-claim
      configMap:
        name: fog-config
        defaultMode: 0755
        items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
    {{ if .Values.rabbitmq.tls.enabled }}        
    - name: rabbitmq-secret
      secret:
        secretName: {{ .Values.rabbitmq.tls.secretName }}
        items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key 
    {{ end }}                   
status: {}
{{ end }}