{{ if .Values.rabbitmq.enabled }}
{{ $svcType := .Values.rabbitmq.service.type }}
{{ $ports := .Values.rabbitmq.service.ports }}
# rabbitmq-service
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    srv: rabbitmq
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  {{ if or (eq .Values.rabbitmq.service.type "NodePort") (eq .Values.rabbitmq.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.rabbitmq.service.externalTrafficPolicy }}
    {{ if and (eq .Values.rabbitmq.service.externalTrafficPolicy "Local") (eq .Values.rabbitmq.service.type "LoadBalancer") }}
  healthCheckNodePort: {{ .Values.rabbitmq.service.healthCheckNodePort }}
    {{ end }}
  {{ end }}
  ports:
    - name: amqp
      port: {{ $ports.amqp.port }}
      targetPort: 5672
      {{ if or (eq $svcType "NodePort") (eq $svcType "LoadBalancer") }}
      nodePort: {{ $ports.amqp.nodePort }}
      {{ end }}
    - name: amqps
      port: {{ $ports.amqps.port }}
      targetPort: 5672
      {{ if or (eq $svcType "NodePort") (eq $svcType "LoadBalancer") }}
      nodePort: {{ $ports.amqps.nodePort }}
      {{ end }}
    - name: dashboard
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Pod
metadata:
  labels:
{{ include "fogcloud.labels" . | indent 4 }}   
    app: rabbitmq
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  containers:
    - env:
        {{ if .Values.rabbitmq.tls.enabled }}
        - name: RABBITMQ_CONFIG_FILE
          value: /etc/rabbitmq/rabbitmq.tls.conf
        {{ else }}
        - name: RABBITMQ_CONFIG_FILE
          value: /etc/rabbitmq/rabbitmq.conf       
        {{ end }}  
      image: {{ .Values.rabbitmq.image }}:{{ .Values.rabbitmq.imageTag }}
      name: rabbitmq
      ports:
        - containerPort: 15672
        - containerPort: 5672
      {{- if .Values.rabbitmq.resources }}
      resources:
{{ toYaml .Values.rabbitmq.resources | indent 8 }}
      {{- end }}
      volumeMounts:
        - mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
          name: rabbitmq-claim
        - mountPath: /etc/rabbitmq/rabbitmq.tls.conf
          subPath: rabbitmq.tls.conf
          name: rabbitmq-claim          
        - mountPath: /etc/rabbitmq/enabled_plugins
          subPath: enabled_plugins
          name: rabbitmq-claim
        {{ if .Values.rabbitmq.tls.enabled }}  
        - mountPath: /etc/rabbitmq/tls.crt
          subPath: tls.crt
          name: rabbitmq-secret
        - mountPath: /etc/rabbitmq/tls.key
          subPath: tls.key
          name: rabbitmq-secret   
        {{ end }}         
  restartPolicy: Always
  volumes:
    - name: rabbitmq-claim
      configMap:
        name: fog-config
        defaultMode: 0755
        items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: rabbitmq.tls.conf
            path: rabbitmq.tls.conf  
          - key: enabled_plugins
            path: enabled_plugins
    {{ if .Values.rabbitmq.tls.enabled }}        
    - name: rabbitmq-secret
      secret:
        secretName: {{ .Values.rabbitmq.tls.secretName }}
        items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key 
    {{ end }}                   
status: {}
{{ end }}