defaults: &defaults
  HTTP_LISTEN: :8200
  GRPC_LISTEN: :8201
  LOG_LEVEL: debug
  GINMODE: debug
  AUTH_KEY: "not-a-secure-key"
  FOGCLOUD_GRPC_URL: 127.0.0.1:4001
  I18N_FILEPATH:
    ZH: /etc/fognotifier/active.zh.json
    EN: /etc/fognotifier/active.en.json

  NATS_URL: nats://localhost:4222
  NATS_USERNAME: fogcloud
  NATS_PASSWORD: root

  SERVER_NOTIFIER_TASK_POOL_SIZE: 50

  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_PASSWORD:
  REDIS_DB: 1
  REDIS_USERNAME:

  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: fogcloud
  POSTGRES_DBNAME: "fogcloud"
  POSTGRES_SSLMODE: disable

  RABBITMQ_TLS: false
  RABBITMQ_HOST: 127.0.0.1
  RABBITMQ_PORT: 5672
  RABBITMQ_USER: rabbitmq
  RABBITMQ_PASSWORD: fogcloud
  RABBITMQ_EVENTS_EX: fogcloud.event_notify
  RABBITMQ_QUEUE_MAX_LENGTH: 1000000

ci:
  <<: *defaults
  REDIS_HOST: redis

  POSTGRES_HOST: postgres

  NATS_URL: nats://fogcloud-nats:4222

development: &development
  <<: *defaults
  AUTH_KEY: "not-a-secure-key"

  FOGCLOUD_GRPC_URL: "fogcloud:4001"

  REDIS_HOST: redis

  NATS_URL: nats://fogcloud-nats:4222

  POSTGRES_HOST: postgres

  RABBITMQ_HOST: rabbitmq

beta:
  <<: *development

production:
  <<: *development
