{{ if eq .Values.etcd.type "internal" }}
{{ $persistence := .Values.etcd.internal.persistence }}
{{ if not $persistence.existed }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    {{ if $persistence.keep }}
    "helm.sh/resource-policy": keep
    {{ end }}
  labels:
    pvc: etcd-data
  name: {{ $persistence.pvc }}
  
spec:
  storageClassName: {{ $persistence.storageClassName }}
  # volumeName: etcd-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ $persistence.storage }}"
status: {}
{{ end }}
{{ end }}