{{ if eq .Values.etcd.type "internal" }}
{{ $persistence := .Values.etcd.internal.persistence }}
{{ if not $persistence.existed }}
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: etcd-pv
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: ""
#   claimRef:
#     name: etcd-pvc
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    pvc: etcd-data
  name: {{ $persistence.pvc }}
  
spec:
  storageClassName: {{ $persistence.storageClassName }}
  # volumeName: etcd-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ $persistence.storage }}"
status: {}
{{ end }}
{{ end }}